# Generated by Django 4.1 on 2022-08-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MovieName', models.CharField(max_length=255)),
                ('ReleasedYear', models.IntegerField(max_length=4)),
                ('Rating', models.FloatField(max_length=4)),
                ('Languages', models.TextField()),
            ],
            options={
                'db_table': 'Movies',
            },
        ),
    ]
